[BOOST-4692] Support chainId in EventAction
rabbitholegg/boost-protocol pull request #83
Opened 2024-09-13 20:40 UTC by topocount

- **[BOOST-4706] Add chainId to event action parameters**
- **[BOOST-4707] support chainid in EventAction**

2024-09-16 14:26 UTC, topocount commented
@Quazia should we configure a new default branch for this repo now that we're mid-audit?

2024-09-16 16:01 UTC, sammccord requested changes
super minor nit

2024-09-16 16:37 UTC, topocount commented on packages/sdk/src/utils.ts
> +export function toRaw<T extends ActionStep | ActionClaimant>(obj: T) {
thanks yeah i never know how whether to let the parameter typing fill out the rest of the name name or not

2024-09-17 12:51 UTC, sammccord approved these changes
:shipit:

2024-09-17 12:52 UTC, sammccord commented
can you also add a changeset? https://github.com/rabbitholegg/boost-protocol?tab=readme-ov-file#changesets--publishing

2024-09-20 02:47 UTC, topocount commented
@sammccord I'm waiting for the audit to "finish" to start pushing changes

2024-09-20 15:56 UTC, merged